name: Create Issue for New Org Member

on:
  repository_dispatch:
    types: [org-member-added]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create issue with summary and description
        run: |
          echo "Creating issue..."
          gh issue create \
            --repo ${{ github.repository }} \
            --title "${{ github.event.client_payload.summary }}" \
            --body "${{ github.event.client_payload.description }}"
        env:
          GH_TOKEN: ${{ secrets.SECRET_TOKEN }}
